# Generated by Django 2.2.4 on 2020-03-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200320_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
